name: Win10RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Activating RDP access
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Setting password
      run: |
        $password = ConvertTo-SecureString "ComplexP@ssw0rd2024!" -AsPlainText -Force
        Set-LocalUser -Name "runneradmin" -Password $password

    - name: Install OpenSSH client
      run: Add-WindowsCapability -Online -Name OpenSSH.Client*

    - name: Expose RDP via Serveo
      run: |
        ssh -o "StrictHostKeyChecking no" -R 3389:localhost:3389 serveo.net > serveo_output.txt 2>&1 &
        Start-Sleep -Seconds 10
        $serveoUrl = (Select-String -Path serveo_output.txt -Pattern "remote forward" | Select-Object -First 1).Line
        echo "RDP Connection URL: $serveoUrl" | Out-File -FilePath rdp_connection.txt

    - name: Display Serveo URL
      run: type rdp_connection.txt
