name: Build and Download Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PowerShell
      uses: actions/setup-pwsh@v2

    - name: Download Files
      run: |
        $ngrokUrl = "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip"
        $startBatUrl = "https://raw.githubusercontent.com/Riders004/rdp/master/start.bat"
        $wallpaperBatUrl = "https://raw.githubusercontent.com/Riders004/rdp/master/download1.jpeg"
        $loopBatUrl = "https://raw.githubusercontent.com/Riders004/rdp/master/loop.bat"

        function DownloadFile {
            param (
                [string]$url,
                [string]$outputPath
            )
            try {
                Invoke-WebRequest -Uri $url -OutFile $outputPath -ErrorAction Stop
                Write-Output "Successfully downloaded $url to $outputPath"
            } catch {
                Write-Error "Failed to download $url. Error: $_"
            }
        }

        Write-Output "Starting downloads..."

        DownloadFile -url $ngrokUrl -outputPath "ngrok.zip"
        DownloadFile -url $startBatUrl -outputPath "start.bat"
        DownloadFile -url $wallpaperBatUrl -outputPath "wallpaper.bat"
        DownloadFile -url $loopBatUrl -outputPath "loop.bat"

        Write-Output "Downloads completed."
      shell: pwsh

    - name: Verify Files
      run: |
        if (!(Test-Path -Path "ngrok.zip")) { throw "ngrok.zip not found!" }
        if (!(Test-Path -Path "start.bat")) { throw "start.bat not found!" }
        if (!(Test-Path -Path "wallpaper.bat")) { throw "wallpaper.bat not found!" }
        if (!(Test-Path -Path "loop.bat")) { throw "loop.bat not found!" }
        Write-Output "All files are successfully downloaded."
      shell: pwsh
